### PR TITLE
Adding event_version to TaskExecutionEvent and TaskExecutionClosure

### PR DESCRIPTION
**Pull request by hamersaw**
# TL;DR
Adding an "event_version" field to the TaskExecutionEvent and TaskExecutionClosure protos to track updates in event reporting format. In the near term this will be used to indicate the updated subtask metadata reporting for map tasks.

## Type
 - [ ] Bug Fix
 - [x] Feature
 - [ ] Plugin

## Are all requirements met?

 - [x] Code completed
 - [x] Smoke tested
 - [x] Unit tests added
 - [x] Code documentation added
 - [x] Any pending items have an associated Issue

## Complete description
^^^

## Tracking Issue
https://github.com/flyteorg/flyte/issues/2288

## Follow-up issue
_NA_

### CODE REVIEW

**Review by katrogan — DISMISSED** [review]

**Review by EngHabu — DISMISSED** [review]
@katrogan this is a continuation of the work you did with node execution events... want to make sure you approve of the approach...

**Comment by katrogan** [comment]
@EngHabu I'm actually a bit confused, because in the accompanying admin PR it looks like we update the event version over the [lifetime of a task execution](https://github.com/flyteorg/flyteadmin/pull/395#discussion_r845501703) which is what I thought PhaseVersion was originally intended for

@hamersaw mind explaining when the event version will change? or is this just hard-coded in propeller somewhere now?

**Comment by hamersaw** [comment]
Sorry to introduce the complexity. We are [hardcoding the taskExecutionEventVersion](https://github.com/flyteorg/flytepropeller/blob/dbb799a860a303186b5bcbb19e4f680cf8ca3c0f/pkg/controller/nodes/task/transformer.go#L17) in propeller just like the current nodeExecutionEventVersion.

I added the ability to [update the taskExecutionEventVersion](https://github.com/flyteorg/flyteadmin/blob/c86a3e41bf736342d752d2535eeefb9f080d871f/pkg/repositories/transformers/task_execution.go#L378-L380) during execution as a minor defense in cases where propeller is updated (or downgraded ... shudders) mid-run. I think handling these cases correctly is extremely difficult, not sure if it's a rabbit hole we want to go down.

**Comment by katrogan** [comment]
got it, the defensive case makes sense 👍

**Review by EngHabu — APPROVED** [review]

**Review by katrogan — APPROVED** [review]

**Pull request merged**
